In [1]:
# 1
import numpy as np 

In [2]:
# 2
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4) The memory size in Bytes required by an rectangular array is (# of rows)(# of cols)(size of one element).

5) Python has a built-in help() function that can access this information and prints the results. For example, to see the documentation of the built-in len function, you can do the following: In [1]: help(len) Help on built-in function len in module builtins: len(...)

In [3]:
# 6
v = np.zeros(10)
v[4] = 1
print(v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [11]:
# 7
z = np.arange(10,50)
print(z)

# 8
x = z[::-1]
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [14]:
# 9
w = np.arange(9).reshape(3,3)
print (w)

# 10
np.nonzero([1,2,0,0,4,0])

[[0 1 2]
 [3 4 5]
 [6 7 8]]


(array([0, 1, 4]),)

In [21]:
# 11
y = np.eye(3)
print (y)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
# 12
z = np.random.uniform((3,3,3))
print (z)

[1.44632283 2.29780593 2.56484212]


In [28]:
# 13
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.011499091160378505 0.9646527672780774


In [18]:
# 14
Z = np.random.random(10)
m = Z.mean()
print (m)


0.4503305711376552


In [41]:
# 15
Z = np.ones((10,10))
Z[1:-1,1:-1]=0
print(Z)

# 16
x = np.ones((3,3))
y = np.pad(x,pad_width=1)
print(y)

# 17
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
nan
False
False
nan
False


In [44]:
# 18
Z = np.diag([1,2,3,4,7])
print (Z)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 7]]


In [58]:
# 19
Z = np.zeros ((8,8), dtype=int)
Z[1::2, ::2]= 1
Z[::2, 1::2] = 1
print (Z)

# 20
print (np.unravel_index(100, (6,7,8)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
(1, 5, 4)


In [51]:
# 21
array= np.array([[0,1], [1,0]])
Z = np.tile(array,(4,4))
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [50]:
# 22
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)

[[0.09085968 0.99765331 0.39323379 0.53861416 1.        ]
 [0.4760491  0.66783637 0.39284361 0.73320766 0.42575159]
 [0.42325481 0.9760227  0.15492818 0.31552435 0.27811591]
 [0.78553746 0.05560538 0.22150316 0.1544141  0.60376346]
 [0.6142452  0.26795322 0.         0.12688125 0.82407473]]


In [69]:
# 23
arr = np.array([2,4],dtype = np.int16)
print(arr.dtype)

int16


In [60]:
# 24
Z= np.dot(np.ones((5,3)), np.ones((3,2)))
print (Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [75]:
# 25
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)


[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [87]:
# 26
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [92]:
# 27
Z <- Z
1j*Z

array([ 0. +0.j,  0. +1.j,  0. +2.j,  0. +3.j, -0. -4.j, -0. -5.j,
       -0. -6.j, -0. -7.j, -0. -8.j,  0. +9.j,  0.+10.j])

In [94]:
# 28
np.array(0)


array(0)

In [96]:
# 29
# we ceate an array
# use np.round


In [ ]:
# 30
# we use mean

In [ ]:
np.array(0)